# /// script
# requires-python = ">=3.11"
# dependencies = ["copier==9.18.2"]
# ///
"""Generate and update projects using Copier, with isolated diff previews."""

from __future__ import annotations

import argparse
import difflib
import keyword
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from copier import run_copy, run_update
from copier.errors import UserMessageError
from plumbum import ProcessExecutionError

DEFAULT_SOURCE = "https://github.com/alexsuslin/gh-project-scaffold.git"


def git(root: Path, *arguments: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(root), "-c", "core.quotepath=false", *arguments],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if result.returncode:
        raise ValueError(result.stderr.strip() or "Git command failed")
    return result.stdout


def require_empty_destination(destination: Path) -> None:
    if destination.is_symlink():
        raise ValueError("Destination must not be a symbolic link")
    if destination.exists():
        if not destination.is_dir():
            raise ValueError("Destination is not a directory")
        if any(path.name != ".git" for path in destination.iterdir()):
            raise ValueError("Create requires an empty destination (an existing .git is allowed)")


def show_created_files(rendered: Path) -> None:
    for path in sorted(rendered.rglob("*")):
        if not path.is_file():
            continue
        name = path.relative_to(rendered).as_posix()
        try:
            content = path.read_text(encoding="utf-8").splitlines(keepends=True)
        except UnicodeError:
            print(f"Create binary file: {name}")
            continue
        print("".join(difflib.unified_diff([], content, fromfile="/dev/null", tofile=name)), end="")


def create_project(args: argparse.Namespace) -> int:
    require_empty_destination(args.destination)
    package_name = args.package or args.name.replace("-", "_").replace(".", "_")
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*", args.name):
        raise ValueError("Invalid distribution name; use a name such as weather-kit")
    if not re.fullmatch(r"[a-z][a-z0-9_]*", package_name) or keyword.iskeyword(package_name):
        raise ValueError("Invalid Python package name")
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9-]{0,38}", args.owner):
        raise ValueError("Invalid GitHub owner")
    data = {
        "project_name": args.name,
        "package_name": package_name,
        "owner": args.owner,
        "description": args.description,
        "visibility": args.visibility,
        "project_license": args.license,
        "copyright_year": datetime.now(UTC).year,
    }
    with tempfile.TemporaryDirectory(prefix="scaffold-create-") as temporary:
        rendered = Path(temporary) / "project"
        run_copy(
            args.source,
            rendered,
            data=data,
            vcs_ref=args.ref,
            defaults=True,
            quiet=True,
            skip_tasks=True,
        )
        if args.preview:
            show_created_files(rendered)
            return 0
        # Recheck after rendering so an intervening user edit cannot be overwritten.
        require_empty_destination(args.destination)
        args.destination.mkdir(parents=True, exist_ok=True)
        shutil.copytree(rendered, args.destination, dirs_exist_ok=True)
    print(f"Created {args.destination}. Review the files, then initialize/commit with Git.")
    return 0


def require_clean_project(destination: Path) -> None:
    root = Path(git(destination, "rev-parse", "--show-toplevel").strip()).resolve()
    if root != destination.resolve():
        raise ValueError("Update must target the root of the generated Git repository")
    if not (destination / ".copier-answers.yml").is_file():
        raise ValueError("No .copier-answers.yml; this project was not generated by Copier")
    if git(destination, "status", "--porcelain", "--untracked-files=all").strip():
        raise ValueError("Update requires a clean Git working tree; commit or stash your changes")


def check_preview_collisions(destination: Path, preview: Path, changed: list[str]) -> None:
    """Refuse collisions with local files before applying any part of an update."""
    tracked = set(git(destination, "ls-files", "-z").split("\0"))
    for name in changed:
        relative = Path(name)
        if relative.is_absolute() or ".." in relative.parts or ".git" in relative.parts:
            raise ValueError(f"Unsafe update path: {name}")
        target = destination / relative
        source = preview / relative
        if source.is_symlink() or target.is_symlink():
            raise ValueError(f"Update requires manual handling of symbolic link: {name}")
        for parent in relative.parents:
            if parent == Path("."):
                continue
            ancestor = destination / parent
            if ancestor.is_symlink() or (ancestor.exists() and not ancestor.is_dir()):
                raise ValueError(f"Update path crosses a non-directory: {name}")
        if target.exists() and name not in tracked:
            raise ValueError(f"Update would overwrite an ignored/local path: {name}")
        if source.exists() and not source.is_file():
            raise ValueError(f"Update requires manual handling of non-file: {name}")


def apply_preview(destination: Path, preview: Path, changed: list[str]) -> None:
    check_preview_collisions(destination, preview, changed)
    for name in changed:
        target = destination / name
        source = preview / name
        if source.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        elif target.is_file():
            target.unlink()


def update_project(args: argparse.Namespace) -> int:
    require_clean_project(args.destination)
    original_head = git(args.destination, "rev-parse", "HEAD").strip()
    with tempfile.TemporaryDirectory(prefix="scaffold-update-") as temporary:
        preview = Path(temporary) / "project"
        git(
            args.destination,
            "clone",
            "--quiet",
            "--no-hardlinks",
            str(args.destination.resolve()),
            str(preview),
        )
        run_update(
            preview,
            vcs_ref=args.ref,
            defaults=True,
            overwrite=True,
            quiet=True,
            skip_tasks=True,
            conflict="inline",
        )
        conflicts = git(preview, "diff", "--name-only", "--diff-filter=U").strip()
        # Include newly generated ignored files so collisions cannot hide from the plan.
        git(preview, "add", "--intent-to-add", "--all", "--force")
        diff = git(preview, "-c", "color.ui=false", "diff", "--no-ext-diff", "HEAD")
        changed = [
            name
            for name in git(preview, "diff", "--no-renames", "--name-only", "-z", "HEAD").split(
                "\0"
            )
            if name
        ]
        if args.preview or conflicts:
            print(diff, end="")
        if conflicts:
            print(
                f"Conflicts require manual resolution; project unchanged:\n{conflicts}",
                file=sys.stderr,
            )
            print(
                "Use copier update in a separate branch to resolve these conflicts.",
                file=sys.stderr,
            )
            return 3
        require_clean_project(args.destination)
        if git(args.destination, "rev-parse", "HEAD").strip() != original_head:
            raise ValueError("Project HEAD changed while preparing update; retry")
        if args.preview:
            # Run collision checks as well, without applying the prepared files.
            check_preview_collisions(args.destination, preview, changed)
            if not diff:
                print("Already up to date.")
            return 0
        apply_preview(args.destination, preview, changed)
    print("Updated template files. Review git diff and commit the changes.")
    return 0


def main() -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    create = commands.add_parser("create", help="Create a project, or preview its files")
    create.add_argument("destination", type=Path)
    create.add_argument("--name", required=True, help="Distribution name, e.g. weather-kit")
    create.add_argument("--package", help="Python import name (derived from --name by default)")
    create.add_argument("--owner", required=True, help="GitHub username or organization")
    create.add_argument("--description", default="A Python project.")
    create.add_argument("--visibility", choices=("public", "private"), default="public")
    create.add_argument("--license", choices=("MIT", "none"), default="MIT")
    create.add_argument(
        "--source", default=DEFAULT_SOURCE, help="Copier Git template URL or local path"
    )
    create.add_argument("--ref", help="Template Git tag or commit (default: latest release)")
    create.add_argument(
        "--preview", action="store_true", help="Show diff without changing destination"
    )
    update = commands.add_parser("update", help="Update a clean generated Git repository")
    update.add_argument("destination", type=Path)
    update.add_argument("--ref", help="New template Git tag or commit (default: latest release)")
    update.add_argument(
        "--preview", action="store_true", help="Calculate update in an isolated clone"
    )
    args = parser.parse_args()
    try:
        return create_project(args) if args.command == "create" else update_project(args)
    except (OSError, ValueError, UserMessageError, ProcessExecutionError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
